services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  docono.company.installer: '@CompanyBundle\Installer'
  CompanyBundle\Installer:
    arguments:
      $bundle: "@=service('kernel').getBundle('CompanyBundle')"

  docono.company.template:
    class: CompanyBundle\Services\Template
    arguments: ['@templating']