services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  docono\Bundle\CompanyBundle\Controller\:
    resource: '../../Controller'
    public: true
    tags: [ 'controller.service_arguments' ]

  docono.company.installer:
    class: docono\Bundle\CompanyBundle\Installer
    arguments:
      $bundle: "@=service('kernel').getBundle('DoconoCompanyBundle')"

  docono\Bundle\CompanyBundle\Installer: '@docono.company.installer'