services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  docono.company.installer: '@CompanyBundle\Installer'
  docono\Bundle\CompanyBundle\Installer:
    arguments:
      $bundle: "@=service('kernel').getBundle('CompanyBundle')"

  docono.company.template:
    class: docono\Bundle\CompanyBundle\Services\Template
    arguments: ['@templating']