twig:
    paths:
        '%kernel.project_dir%/app/Resources/views/': docono.company
        '%kernel.project_dir%/vendor/docono/company-bundle/src/CompanyBundle/Resources/views/': docono.company

pimcore:
    documents:
        tags:
            map:
                company: \CompanyBundle\Model\Document\Tag\Company